# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'Git2AzureDevOps'
    userRepository: 'hteo1337/UiRobot-AWS'
    defaultVersionType: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)/_hteo1337_UiRobot-AWS/'
    continueOnError: true
    condition: succeededOrFailed()
    
- task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
  displayName: 'S3 Upload: git2s3-aws'
  inputs:
    awsCredentials: aws
    regionName: 'eu-west-2'
    bucketName: 'git2s3-aws'
    sourceFolder: '$(System.ArtifactsDirectory)/_hteo1337_UiRobot-AWS/'
    filesAcl: 'public-read'
    createBucket: true