# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'
 

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '0c694140-b8c6-45da-ad51-0164eac76170'
    definition: '9'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    tags: 'latest'
    targetPath: '$(System.DefaultWorkingDirectory)/_hteo1337_UiRobot-AWS/'

# - task: DownloadGitHubRelease@0
#   inputs:
#       connection: 'Git2AzureDevOps'
#       userRepository: 'hteo1337/UiRobot-AWS'
#       defaultVersionType: 'latest'
#       downloadPath: '$(System.DefaultWorkingDirectory)/_hteo1337_UiRobot-AWS/'
#       continueOnError: true
#       condition: succeededOrFailed()

- task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
  displayName: 'S3 Upload: git-test'
  inputs:
    awsCredentials: aws
    regionName: 'eu-west-2'
    bucketName: 'git-test-hteox'
    sourceFolder: '$(System.DefaultWorkingDirectory)/_hteo1337_UiRobot-AWS/uirobot.yml'
    filesAcl: 'public-read'
    createBucket: true
  continueOnError: true
  condition: succeededOrFailed()
